### PR TITLE
[SST-18760] add created_at and updated_at to Watchlist model

### PR DESCRIPTION
**Pull request by jaime-traction**
### Description
Added `created_at` and `updated_at` to the watchlist model

### Changelog
- Added `created_at` and `updated_at` to `Watchlist.v1.yaml`

## Notes (can delete this section after doing):
- [ ] Start at least one of your commits with your wrike ticket in the following format, `[#1234] Your concise and explicit commit message`
- [ ] Use the `Squash and Merge` button to combine your commits in to one final commit (with the wrike ticket) to go in to master

### CODE REVIEW

**Comment by prescottie** [comment]
failing on validating_yaml 👀

**Comment by jaime-traction** [comment]
> failing on validating_yaml 👀

@prescottie It has something to do with the version of `spectral` whatever that is... lol @himanshu8garg fixed it so it is now okay

**Comment by prescottie** [comment]
DON"T FORGET TO BUMP THE VERSION NUMBER.

**Comment by jaime-traction** [comment]
> DON"T FORGET TO BUMP THE VERSION NUMBER.

@prescottie I did not know I needed to do that 😱 Hopefully, I updated the version in the correct file (`openapi.yml`)

**Review by prescottie — APPROVED** [review]

**Review by pluus — APPROVED** [review]

**Review by pluus — APPROVED** [review]

**Review by ErebusBat — APPROVED** [review]

**Pull request merged**
