### PR TITLE
SST-15845 Feature/invite on premise

### PR DESCRIPTION
**Pull request by dkohlruss**
### Description
In the current web app, we refer to on_premise in the invites table within the appointments tab in the locations view.  However, we currently do not expose that via v3, which is where we are fetching invites on that view.  Therefore, we just need to add this boolean to our docs before it can be exposed.

Edit: After chatting with product, this actually should be `checked_in` instead of `on_premise`.  Making the change now.

### Changelog
- `InviteDetail.v1.yaml` -> Added `on_premise` boolean property

## Notes (can delete this section after doing):
- [x] Start at least one of your commits with your wrike ticket in the following format, `[#1234] Your concise and explicit commit message`
- [ ] Use the `Squash and Merge` button to combine your commits in to one final commit (with the wrike ticket) to go in to master

### CODE REVIEW

**Review by stevenallen05 — DISMISSED** [review]

**Review by prescottie — APPROVED** [review]

**Comment by prescottie** [comment]
> Therefore, we just need to add this boolean to our docs before it can be exposed.
🌵 I think its suppose to be the other way around... we are suppose to put it in the API before we add it to our docs. I think its better to have undocumented functionality than documented functionality that isn't there yet... now I am assuming since its such a small change the two will go out very close to each other, so it won't cost us anything, but could pose a potential problem with bigger changes/longer times between the two deployments

**Comment by dkohlruss** [comment]
This needs to be changed to checked_in, because as it turns out on_premise doesn't appear to do anything

**Comment by dkohlruss** [comment]
After chatting with product, this actually should be checked_in instead of on_premise. Making the change now.

**Review by prescottie — APPROVED** [review]

**Review by clrobinson-traction — APPROVED** [review]
Seems appropriate. 🌮

**Pull request merged**
